---
# handlers/main.yml: Handlers for RocketChat.Ansible
  - name: Reload the Nginx service
    service: name=nginx state=reloaded

  - name: Upgrade Rocket.Chat
    include: ../tasks/upgrade.yml
    tags:
      - upgrade

  - name: Reload PM2 config
    shell: pm2 reload pm2-rocket-chat.json
    args:
      chdir: /var/www/rocket.chat
